- hosts: all
  become: true

  tasks:
    - name: Install utilities
      yum:
        name: "{{ item }}"
      loop:
        - tcpdump
        - bind-utils
        - vim

- hosts: router
  become: true

  tasks:
    - name: Enable ip forwarding in router
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: Ensure firewalld is running
      systemd:
        state: started
        name: firewalld
        enabled: true
        #    - name: Enable NAT to outside
        #      command: "firewall-cmd --permanent --direct --passthrough ipv4 -t nat -I POSTROUTING -o enp0s3 -j MASQUERADE -s 192.168.0.0/16"
    - name: Add internal NICs to internal zone
      firewalld:
        interface: "{{ item }}"
        zone: internal
        state: enabled
      loop:
        - "enp0s8"
        - "enp0s9"
        - "enp0s10"
    - name: NAT Masquerade default zone (usually public)
      firewalld:
        masquerade: yes
        state: enabled
        permanent: yes
    - name: Allow outgoing connections
      command: "firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -s 192.168.0.0/16 -o enp0s3 -j ACCEPT"
    - name: Accept incoming established/active connections
      command: "firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i enp0s3 -d 192.168.0.0/16 -m state --state RELATED,ESTABLISHED -j ACCEPT"

    - name: Reload firewall
      command: "firewall-cmd --reload"

- hosts: all:!router
  become: true

  vars:
    default_gateways: {
      'client': '192.168.101.1', 'infra': '192.168.102.1', 'cin': '192.168.103.1'
    }

  tasks:
    - name: Remove default gateway
      command: "ip route del default"
      ignore_errors: "true"
    - name: Add default gateway to router
      command: "ip route add default via {{ default_gateways[inventory_hostname] }}"

