---
- name: pxe | Create tftpboot ipxe directory
  file:
    path: /var/lib/tftpboot/ipxe
    state: directory

- name: pxe | Configure TFTP iPXE loader
  template:
    src: loader.ipxe.j2
    dest: /var/lib/tftpboot/ipxe/loader.ipxe

- name: pxe | Download undionly (ipxe)
  get_url:
    dest: /var/lib/tftpboot/undionly.kpxe
    url: http://boot.ipxe.org/undionly.kpxe
    checksum: sha256:810d8818c2fd10827d5c154307332acbc59f62ceb2008e85c4a40582be6c87c0

- name: pxe | Download Talos vmlinuz and initrd
  get_url:
    dest: "/var/lib/tftpboot/ipxe/{{ item.name }}"
    url: "{{ item.url }}"
    #checksum: "sha256:{{ item.sha256 }}"
  loop:
    - name: vmlinuz
      url: https://github.com/talos-systems/talos/releases/download/v0.3.0-beta.0/vmlinuz
      sha256: e5990c539b5884400f88d98d3033da2c84e39fb98d91e97308192cc979e2018f
      sha256: e5e7266b2e889354346f37f140ef8f412105f3bb67693d15b1c7121153e53411
    - name: initramfs.xz
      url: https://github.com/talos-systems/talos/releases/download/v0.3.0-beta.0/initramfs.xz
      sha256: d4d723be926b57d63b7d163936eb474c5c727b43e81e4eda174d372bd182f003

