---
- name: Configure network interfaces
  template:
    src: ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.device }}
  loop:
    - device: eth1
      ip: "{{ host_ips[inventory_hostname] }}"
      netmask: 255.255.255.0
      gateway: "{{ default_gateways[inventory_hostname] }}"
  notify: network | restart

- name: Set DNS nameserver
  lineinfile:
    path: /etc/resolv.conf
    regexp: "^nameserver"
    line: "nameserver 192.168.102.2"
    state: present
- name: Set DNS search domain
  lineinfile:
    path: /etc/resolv.conf
    line: "search virtual.net"
    state: present
