- hosts: all
  become: true

  tasks:
    - name: Install utilities
      yum:
        name: "{{ item }}"
      loop:
        - tcpdump
        - bind-utils
        - vim
        - tmux

- hosts: infra
  become: true
  tasks:
    - yum:
        name: "{{ item }}"
      loop:
        - bind
        - python-gobject
        - NetworkManager-glib

- hosts: all
  become: true
  tasks:
    - name: Remove nameservers in /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: "^nameserver"
        state: absent

- hosts: all:!router
  become: true

  vars:
    host_ips: {
      'client': '192.168.101.2/24', 'infra': '192.168.102.2/24', 'cin': '192.168.103.2/24'
    }
    default_gateways: {
      'client': '192.168.101.1', 'infra': '192.168.102.1', 'cin': '192.168.103.1'
    }

  tasks:
    - name: Configure internal network IP
      command: "ip a add {{ host_ips[inventory_hostname] }} dev eth1"
      ignore_errors: "true"
    - name: Remove default gateway
      command: "ip route del default"
      ignore_errors: "true"
    - name: Add default gateway to router
      command: "ip route add default via {{ default_gateways[inventory_hostname] }}"
      ignore_errors: "true"
    - name: Set DNS nameserver
      lineinfile:
        path: /etc/resolv.conf
        regexp: "^nameserver"
        line: "nameserver 192.168.102.2"
        state: present
    - name: Set DNS search domain
      lineinfile:
        path: /etc/resolv.conf
        line: "search virtual.net"
        state: present

- hosts: router
  become: true

  tasks:
    - name: Enable ip forwarding in router
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: Ensure firewalld is running
      systemd:
        state: started
        name: firewalld
        enabled: true
        #    - name: Enable NAT to outside
        #      command: "firewall-cmd --permanent --direct --passthrough ipv4 -t nat -I POSTROUTING -o enp0s3 -j MASQUERADE -s 192.168.0.0/16"
    - name: Add internal NICs to internal zone
      firewalld:
        interface: "{{ item }}"
        zone: trusted # should be "internal"!!! TODO: but then can't reach per DNS
                      # tcpdump says:
                      #   IP router > 192.168.101.2: ICMP host 192.168.102.2 unreachable - admin prohibited, length 64
        state: enabled
      loop:
        - "eth1"
        - "eth2"
        - "eth3"
    - name: NAT Masquerade default zone (usually public)
      firewalld:
        masquerade: yes
        state: enabled
        permanent: yes
    - name: Allow outgoing connections
      command: "firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -s 192.168.0.0/16 -o eth0 -j ACCEPT"
    - name: Accept incoming established/active connections
      command: "firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i eth0 -d 192.168.0.0/16 -m state --state RELATED,ESTABLISHED -j ACCEPT"

    - name: Reload firewall
      command: "firewall-cmd --reload"

- hosts: infra
  become: true
  roles:
    - bind




