---
- hosts: all
  become: true

  tasks:
    - name: Install utilities
      yum:
        name: "{{ item }}"
      loop:
        - tcpdump
        - bind-utils
        - vim
        - tmux

- hosts: all:!router
  become: true

  roles:
    - provision

- hosts: router
  become: true
  roles:
    - router

- hosts: infra
  become: true
  roles:
    - bind
    - dhcp
    - talos
