---
- hosts: all
  become: true
  tasks:
    - name: Install utilities
      yum:
        name: "{{ item }}"
      loop:
        - tcpdump
        - bind-utils

# First install required components on infra host to support
# infrastructure
- hosts: infra
  become: true
  roles:
    - infra-network
    - bind
    - infra-dns
    - dhcp
    - talos

- hosts: router
  become: true
  roles:
    - router

- hosts: all:!router
  become: true
  roles:
    - infra-network
    - infra-dns
