---
- name: Set DNS nameserver
  lineinfile:
    path: /etc/resolv.conf
    regexp: "^nameserver"
    line: "nameserver 192.168.102.2"
    state: present
- name: Set DNS search domain
  lineinfile:
    path: /etc/resolv.conf
    line: "search virtual.net"
    state: present
