---
- name: Enable ip forwarding in router
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Ensure firewalld is running
  systemd:
    state: started
    name: firewalld
    enabled: true

#- name: Allow outgoing connections
#  #command: "firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -s 192.168.0.0/16 -o eth0 -j ACCEPT"
#  command: "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -s 10.0.2.0/24 -o eth0 -j ACCEPT"
#- name: Accept incoming established/active connections
#  #command: "firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i eth0 -d 192.168.0.0/16 -m state --state RELATED,ESTABLISHED -j ACCEPT"
#  command: "firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -i eth0 -d 10.0.2.0/24 -m state --state RELATED,ESTABLISHED -j ACCEPT"
#- name: Reload firewall
#  command: "firewall-cmd --reload"
#  command: "systemctl restart firewalld"

- name: Remove internal interfaces from public zone
  firewalld:
    interface: "{{ item }}"
    state: disabled
    zone: public
    permanent: yes
    immediate: yes
  loop:
    - eth1
    - eth2

- name: Add internal NICs to internal zone
  firewalld:
    source: "{{ item.source }}"
    zone: "{{ item.zone }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - source: 192.168.102.0/24
      zone: trusted # should be "internal"!!! TODO: but then can't reach per DNS
                    # tcpdump says:
                    #   IP router > 192.168.101.2: ICMP host 192.168.102.2 unreachable - admin prohibited, length 64
    - source: 10.0.2.0/24
      zone: public

- name: NAT Masquerade public zone
  firewalld:
    zone: public
    masquerade: yes
    state: enabled
    permanent: yes
    immediate: yes
  #command: "firewall-cmd --permanent --direct --passthrough ipv4 -t nat -I POSTROUTING -o enp0s3 -j MASQUERADE -s 192.168.0.0/16"

#- name: Enable DNS/NTP service on public zone
#  firewalld:
#    zone: public
#    service: ntp
#    state: enabled
#    permanent: yes
#    immediate: yes
#  loop:
#    - dns
#    - ntp
